project:
  type: website
  output-dir: docs
  

website:
  title: "AP601 Capstone"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: intro.qmd
        text: Introduction
      - text: Analysis
        href: Faculty.qmd
      - href: Implications.qmd
        text: Implications
      - href: Limitations.qmd
        text: Limitations
      - href: Conclusion.qmd
        text: Conclusion
      - href: References.qmd
        text: References
      - about.qmd
      
  sidebar:
    style: floating
    contents:
      - section: "Main Analysis"
        contents:
          - Faculty.qmd
          - Students.qmd
          - Admissions.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true
    versioned: true
    include-in-header: meta-nocache.html

editor: visual

