---
title: "Implications"
format: html
---

As a former student of Boston University and current administrator at Boston University, much of my life has been spent within the BU community. I know the policies like the back of my hand, I can name every HUB requirement, I have a breadth of connections with colleagues across the university, and I spend my days and evenings helping others connect with the institution in the ways I have. I can recite Boston University's pitch (WORLD-CLASS R1 RESEARCH INSTITUTION) and why it is special, and I can repeat the various accomplishments (FIRST WOMAN PHD! MARTIN LUTHER KING JR!!). However, this project showed me what BU is beyond the narrative. While it is important to know the proud history of the institution you are affiliated with, being able to see long-term trends will specifically help me in various capacities of my job. I can see now that women are not obtaining tenure and can support our faculty in their tenure and promotion cases. I can see the tuition increase and the subsequent rise in financial aid and can communicate that to students. I can perceive the BU community from a bird's-eye view and bring that knowledge into my everyday interactions.

For a long time, much of the information about BU has been conveyed to me through the grapevine and through anecdotes—a student sharing that their aid package wasn’t enough, a staff member saying that female faculty aren’t being retained, or a graduate student sharing that they feel unsupported and are leaving the program. These are not secrets—they’re available on IPEDS in number form and just need to be organized into graphs in order to pull back the mask on BU.
